# shared/config.py
from dotenv import load_dotenv
import os

load_dotenv(override=True)

PRODUCTION = os.getenv('PRODUCTION', 'false').lower() == 'true'
DEBUG = os.getenv('DEBUG', 'false').lower() == 'true'

if PRODUCTION:
    DEBUG = False

DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_KEY = os.getenv("SECRET_KEY")
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")
ALGORITHM = os.getenv("ALGORITHM")

# 
EXTERNAL_URL = os.getenv("EXTERNAL_URL")
MAX_YEAR_DATE = os.getenv("MAX_YEAR_DATE")
PAGE_LOADING_WAITING_TIME_IN_SECONDS = os.getenv("PAGE_LOADING_WAITING_TIME_IN_SECONDS")
PAGE_MAX_RETRY=os.getenv("PAGE_MAX_RETRY")
PAGE_RETRY_DELAY_TIME_IN_SECONDS=os.getenv("PAGE_RETRY_DELAY_TIME_IN_SECONDS")
SELENIUM_DRIVE_ARGS=os.getenv("SELENIUM_DRIVE_ARGS")

# 
CACHED_TAB_PRODUCTIONS_FILE_NAME = os.getenv("CACHED_TAB_PRODUCTIONS_FILE_NAME")
CACHED_TAB_PROCESSINGN_FILE_NAME = os.getenv("CACHED_TAB_PROCESSINGN_FILE_NAME")
CACHED_TAB_COMMERCIALIZATION_FILE_NAME = os.getenv("CACHED_TAB_COMMERCIALIZATION_FILE_NAME")
CACHED_TAB_IMPORTATION_FILE_NAME = os.getenv("CACHED_TAB_IMPORTATION_FILE_NAME")
CACHED_TAB_EXPORTATION_FILE_NAME = os.getenv("CACHED_TAB_EXPORTATION_FILE_NAME")